// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2GPtJ61S_vqS32uUQq37TfHoe4hN4X7E',
    appId: '1:748639497070:android:0f6c8f09297cd07710af7f',
    messagingSenderId: '748639497070',
    projectId: 'brew-9089c',
    storageBucket: 'brew-9089c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZrrsZAsUwL-tnJUr8wP4GuPxl_QC3NNE',
    appId: '1:748639497070:ios:54a8f31aa63a728d10af7f',
    messagingSenderId: '748639497070',
    projectId: 'brew-9089c',
    storageBucket: 'brew-9089c.firebasestorage.app',
    iosBundleId: 'com.example.brew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZrrsZAsUwL-tnJUr8wP4GuPxl_QC3NNE',
    appId: '1:748639497070:ios:54a8f31aa63a728d10af7f',
    messagingSenderId: '748639497070',
    projectId: 'brew-9089c',
    storageBucket: 'brew-9089c.firebasestorage.app',
    iosBundleId: 'com.example.brew',
  );
}
